// Mock responses for development when the Demo Gateway is not running.
import {
  WorkActionType,
  WorkActionStatus,
  WorkActionCategory,
  WorkActionPriority,
  WorkCompletionStatus,
  ConfidenceLevel,
  VerificationReportStatus,
  EvidenceType,
  type PredictionResponse,
  type MatchResponse,
  type WorkVerificationReportV2,
  type WorkAction,
  type ProviderScore,
} from '@/data/types';

// ─── Hot Water Heater (default) ───────────────────────────────────────────────

export const MOCK_QUALIFY_RESPONSE: PredictionResponse = {
  is_recall: false,
  is_recall_v2: false,
  is_estimate: false,
  is_parts_and_order: false,
  service_type_id: 'svc-type-plumbing-water-heater',
  service_line_id: 'svc-line-plumbing',
  is_project_work: false,
  enriched_ticket_scope:
    'Water heater pilot light out. No hot water at commercial dental office. Requires pilot inspection, cleaning, and re-ignition.',
  work_scope:
    'Inspect water heater pilot assembly at commercial dental facility. Clean pilot orifice and thermocouple. Re-ignite pilot per manufacturer procedure. Test hot water supply at nearest fixture. Verify steady pilot flame and normal water temperature recovery. Document findings and leave unit operational.',
  work_type: 'REPAIR',
  asset: 'Commercial Water Heater',
  location: 'Utility Room',
  special_instructions:
    'Contact store manager on arrival. Building requires sign-in at front desk. Unit is in rear utility room, key from manager.',
  recommendation_id: 'rec-a1b2c3d4',
  work_complexity: 'SIMPLE',
};

export const MOCK_WORK_ACTIONS: WorkAction[] = [
  {
    action_id: 'wa-000',
    type: WorkActionType.WORK_ACTION_TYPE_DOCUMENTATION,
    category: WorkActionCategory.WORK_ACTION_CATEGORY_OTHERS,
    priority: WorkActionPriority.WORK_ACTION_PRIORITY_HIGH,
    description: 'Identify yourself to site management at front desk, sign in, and be escorted to the utility room service location',
    status: WorkActionStatus.WORK_ACTION_STATUS_TODO,
    creation_context: {
      rationale: 'Commercial dental office requires sign-in and escort per special instructions. Establishing site contact ensures access and accountability.',
      evidences: [{ id: 'ev-spec-000', type: EvidenceType.EVIDENCE_TYPE_WORK_SCOPE, rationale: 'Special instructions specify front desk sign-in and manager escort.' }],
    },
  },
  {
    action_id: 'wa-001a',
    type: WorkActionType.WORK_ACTION_TYPE_DOCUMENTATION,
    category: WorkActionCategory.WORK_ACTION_CATEGORY_INSPECTION,
    priority: WorkActionPriority.WORK_ACTION_PRIORITY_HIGH,
    description: 'Take before photos of water heater unit, pilot assembly, and surrounding area documenting pre-service condition',
    status: WorkActionStatus.WORK_ACTION_STATUS_TODO,
    creation_context: {
      rationale: 'Before photos establish baseline condition for quality verification and protect both parties in scope disputes.',
      evidences: [],
    },
  },
  {
    action_id: 'wa-001',
    type: WorkActionType.WORK_ACTION_TYPE_ESSENTIAL,
    category: WorkActionCategory.WORK_ACTION_CATEGORY_INSPECTION,
    priority: WorkActionPriority.WORK_ACTION_PRIORITY_HIGH,
    description: 'Inspect pilot assembly and thermocouple for damage, corrosion, or carbon buildup',
    status: WorkActionStatus.WORK_ACTION_STATUS_TODO,
    creation_context: {
      rationale: 'Customer reported pilot light issue. Inspection of pilot assembly is required to determine root cause before any cleaning or re-ignition attempt.',
      evidences: [{ id: 'ev-scope-001', type: EvidenceType.EVIDENCE_TYPE_WORK_SCOPE, rationale: 'Work scope identifies pilot assembly inspection as primary task.' }],
    },
  },
  {
    action_id: 'wa-002',
    type: WorkActionType.WORK_ACTION_TYPE_ESSENTIAL,
    category: WorkActionCategory.WORK_ACTION_CATEGORY_CLEANING,
    priority: WorkActionPriority.WORK_ACTION_PRIORITY_HIGH,
    description: 'Clean pilot orifice, thermocouple tip, and burner assembly — remove soot and carbon deposits',
    status: WorkActionStatus.WORK_ACTION_STATUS_TODO,
    creation_context: {
      rationale: 'Thorough cleaning of all pilot components is necessary to ensure proper gas flow and reliable ignition.',
      evidences: [],
    },
  },
  {
    action_id: 'wa-003',
    type: WorkActionType.WORK_ACTION_TYPE_ESSENTIAL,
    category: WorkActionCategory.WORK_ACTION_CATEGORY_REPAIR,
    priority: WorkActionPriority.WORK_ACTION_PRIORITY_HIGH,
    description: 'Re-ignite pilot light following manufacturer procedure and verify stable, continuous blue flame',
    status: WorkActionStatus.WORK_ACTION_STATUS_TODO,
    creation_context: {
      rationale: 'Re-ignition is the primary resolution objective. Flame must be steady and blue to confirm safe and complete repair.',
      evidences: [],
    },
  },
  {
    action_id: 'wa-004',
    type: WorkActionType.WORK_ACTION_TYPE_AUXILIARY,
    category: WorkActionCategory.WORK_ACTION_CATEGORY_TESTING,
    priority: WorkActionPriority.WORK_ACTION_PRIORITY_MEDIUM,
    description: 'Test hot water supply at nearest fixture — run water and confirm temperature recovery to operational level',
    status: WorkActionStatus.WORK_ACTION_STATUS_TODO,
    creation_context: {
      rationale: 'End-to-end functional test confirms repair success and validates that service has been fully restored for the customer.',
      evidences: [],
    },
  },
  {
    action_id: 'wa-005',
    type: WorkActionType.WORK_ACTION_TYPE_DOCUMENTATION,
    category: WorkActionCategory.WORK_ACTION_CATEGORY_INSPECTION,
    priority: WorkActionPriority.WORK_ACTION_PRIORITY_HIGH,
    description: 'Take after photos of pilot assembly with flame visible, water heater controls, and faucet running hot water confirming service restoration',
    status: WorkActionStatus.WORK_ACTION_STATUS_TODO,
    creation_context: {
      rationale: 'After photos provide photographic proof of completion for AI quality verification and customer records.',
      evidences: [],
    },
  },
  {
    action_id: 'wa-006',
    type: WorkActionType.WORK_ACTION_TYPE_DOCUMENTATION,
    category: WorkActionCategory.WORK_ACTION_CATEGORY_OTHERS,
    priority: WorkActionPriority.WORK_ACTION_PRIORITY_HIGH,
    description: 'Clean up work area, return utility room to pre-service condition, and obtain site manager signature confirming hot water restoration before departure',
    status: WorkActionStatus.WORK_ACTION_STATUS_TODO,
    creation_context: {
      rationale: 'Site cleanliness and manager sign-off close the service loop and confirm customer satisfaction before the provider leaves the property.',
      evidences: [],
    },
  },
];

function makeProviders(base: ProviderScore[], extras: Omit<ProviderScore, 'tags'>[]): ProviderScore[] {
  return [
    ...base,
    ...extras.map((p) => ({ ...p, tags: [] as ProviderScore['tags'] })),
  ];
}

export const MOCK_MATCH_RESPONSE: MatchResponse = {
  total_matched: 51,
  providers: makeProviders(
    [
      {
        provider_id: 'prov-001',
        provider_name: 'Summit Plumbing Solutions',
        provider_address_id: 'addr-001',
        score: 94,
        is_probationary_provider: false,
        technician_count: 8,
        provider_property_distance_in_miles: 6.2,
        tags: [],
        is_provider_recommended_for_job: true,
        ai_rationale:
          'Summit has completed 12 plumbing jobs at this Heartland Dental location with a 100% acceptance rate and zero defects. They are the most reliable choice for a same-day emergency at this property and are currently available.',
        confidence: ConfidenceLevel.CONFIDENCE_LEVEL_HIGH,
        behavior_labels: ['property_veteran', 'reliable_acceptor'],
        speed_score: 83,
        quality_score: 90,
        cost_score: 84,
        rating: 4.7,
        review_count: 452,
        jobs_completed: 1444,
        scorecard_details: {
          speed: { overall: 83, on_time_arrival: 81, time_to_work_done: 89 },
          quality: { overall: 90, first_time_complete: 82, defect_free_jobs: 96, app_compliance: 92 },
          cost: { overall: 84, used_under_nte: 75, dispute_free: 93 },
        },
      },
      {
        provider_id: 'prov-002',
        provider_name: 'Central Illinois Mechanical',
        provider_address_id: 'addr-002',
        score: 87,
        is_probationary_provider: false,
        technician_count: 14,
        provider_property_distance_in_miles: 8.7,
        tags: [],
        is_provider_recommended_for_job: true,
        ai_rationale:
          'Strong regional player with 3 years of Heartland Dental history across 6 locations. High performance scorecard and certified Avetta provider. Reliable for emergency dispatch.',
        confidence: ConfidenceLevel.CONFIDENCE_LEVEL_HIGH,
        behavior_labels: ['customer_veteran', 'high_performance_score'],
        speed_score: 79,
        quality_score: 88,
        cost_score: 91,
        rating: 4.5,
        review_count: 218,
        jobs_completed: 873,
        scorecard_details: {
          speed: { overall: 79, on_time_arrival: 77, time_to_work_done: 84 },
          quality: { overall: 88, first_time_complete: 85, defect_free_jobs: 91, app_compliance: 89 },
          cost: { overall: 91, used_under_nte: 88, dispute_free: 95 },
        },
      },
      {
        provider_id: 'prov-003',
        provider_name: 'Midwest Pro Services',
        provider_address_id: 'addr-003',
        score: 81,
        is_probationary_provider: false,
        technician_count: 6,
        provider_property_distance_in_miles: 11.3,
        tags: [],
        is_provider_recommended_for_job: true,
        ai_rationale:
          'Qualified plumbing provider with solid on-time arrival history and defect-free completion rate. Broader geographic coverage means slightly longer response but strong capacity available today.',
        confidence: ConfidenceLevel.CONFIDENCE_LEVEL_MEDIUM,
        behavior_labels: ['on_time_arrival', 'defect_free_completion'],
        speed_score: 74,
        quality_score: 85,
        cost_score: 79,
        rating: 4.3,
        review_count: 124,
        jobs_completed: 392,
        scorecard_details: {
          speed: { overall: 74, on_time_arrival: 86, time_to_work_done: 71 },
          quality: { overall: 85, first_time_complete: 80, defect_free_jobs: 94, app_compliance: 82 },
          cost: { overall: 79, used_under_nte: 72, dispute_free: 88 },
        },
      },
    ],
    [
      { provider_id: 'prov-004', provider_name: 'Illinois Plumbing & Mechanical', provider_address_id: 'addr-004', score: 78, is_probationary_provider: false, technician_count: 5, provider_property_distance_in_miles: 12.1, is_provider_recommended_for_job: false, confidence: ConfidenceLevel.CONFIDENCE_LEVEL_UNSPECIFIED, behavior_labels: [] },
      { provider_id: 'prov-005', provider_name: 'Heartland HVAC Services', provider_address_id: 'addr-005', score: 75, is_probationary_provider: false, technician_count: 9, provider_property_distance_in_miles: 13.4, is_provider_recommended_for_job: false, confidence: ConfidenceLevel.CONFIDENCE_LEVEL_UNSPECIFIED, behavior_labels: ['reliable_acceptor'] },
      { provider_id: 'prov-006', provider_name: 'Midwest Water Works', provider_address_id: 'addr-006', score: 73, is_probationary_provider: false, technician_count: 4, provider_property_distance_in_miles: 14.9, is_provider_recommended_for_job: false, confidence: ConfidenceLevel.CONFIDENCE_LEVEL_UNSPECIFIED, behavior_labels: [] },
      { provider_id: 'prov-007', provider_name: 'Prairie State Plumbing', provider_address_id: 'addr-007', score: 71, is_probationary_provider: false, technician_count: 7, provider_property_distance_in_miles: 16.2, is_provider_recommended_for_job: false, confidence: ConfidenceLevel.CONFIDENCE_LEVEL_UNSPECIFIED, behavior_labels: [] },
      { provider_id: 'prov-008', provider_name: 'Central IL Pipe & Drain', provider_address_id: 'addr-008', score: 69, is_probationary_provider: false, technician_count: 3, provider_property_distance_in_miles: 17.5, is_provider_recommended_for_job: false, confidence: ConfidenceLevel.CONFIDENCE_LEVEL_UNSPECIFIED, behavior_labels: [] },
      { provider_id: 'prov-009', provider_name: 'Bloomington Mechanical', provider_address_id: 'addr-009', score: 67, is_probationary_provider: false, technician_count: 6, provider_property_distance_in_miles: 18.8, is_provider_recommended_for_job: false, confidence: ConfidenceLevel.CONFIDENCE_LEVEL_UNSPECIFIED, behavior_labels: ['on_time_arrival'] },
      { provider_id: 'prov-010', provider_name: 'McLean County Plumbing', provider_address_id: 'addr-010', score: 65, is_probationary_provider: false, technician_count: 5, provider_property_distance_in_miles: 20.1, is_provider_recommended_for_job: false, confidence: ConfidenceLevel.CONFIDENCE_LEVEL_UNSPECIFIED, behavior_labels: [] },
      { provider_id: 'prov-011', provider_name: 'Normal Plumbing Co.', provider_address_id: 'addr-011', score: 63, is_probationary_provider: false, technician_count: 4, provider_property_distance_in_miles: 21.4, is_provider_recommended_for_job: false, confidence: ConfidenceLevel.CONFIDENCE_LEVEL_UNSPECIFIED, behavior_labels: [] },
      { provider_id: 'prov-012', provider_name: 'Tri-County Mechanical', provider_address_id: 'addr-012', score: 61, is_probationary_provider: false, technician_count: 8, provider_property_distance_in_miles: 23.0, is_provider_recommended_for_job: false, confidence: ConfidenceLevel.CONFIDENCE_LEVEL_UNSPECIFIED, behavior_labels: [] },
      { provider_id: 'prov-013', provider_name: 'Capital City Plumbing', provider_address_id: 'addr-013', score: 59, is_probationary_provider: false, technician_count: 6, provider_property_distance_in_miles: 24.5, is_provider_recommended_for_job: false, confidence: ConfidenceLevel.CONFIDENCE_LEVEL_UNSPECIFIED, behavior_labels: [] },
      { provider_id: 'prov-014', provider_name: 'Lincoln Land Plumbing', provider_address_id: 'addr-014', score: 57, is_probationary_provider: false, technician_count: 5, provider_property_distance_in_miles: 26.2, is_provider_recommended_for_job: false, confidence: ConfidenceLevel.CONFIDENCE_LEVEL_UNSPECIFIED, behavior_labels: [] },
      { provider_id: 'prov-015', provider_name: 'Peoria Plumbing Group', provider_address_id: 'addr-015', score: 55, is_probationary_provider: false, technician_count: 11, provider_property_distance_in_miles: 28.7, is_provider_recommended_for_job: false, confidence: ConfidenceLevel.CONFIDENCE_LEVEL_UNSPECIFIED, behavior_labels: [] },
      { provider_id: 'prov-016', provider_name: 'Decatur Mechanical Services', provider_address_id: 'addr-016', score: 53, is_probationary_provider: false, technician_count: 7, provider_property_distance_in_miles: 30.1, is_provider_recommended_for_job: false, confidence: ConfidenceLevel.CONFIDENCE_LEVEL_UNSPECIFIED, behavior_labels: [] },
      { provider_id: 'prov-017', provider_name: 'Springfield Plumbing', provider_address_id: 'addr-017', score: 51, is_probationary_provider: false, technician_count: 9, provider_property_distance_in_miles: 32.5, is_provider_recommended_for_job: false, confidence: ConfidenceLevel.CONFIDENCE_LEVEL_UNSPECIFIED, behavior_labels: [] },
      { provider_id: 'prov-018', provider_name: 'Eastern IL Plumbing', provider_address_id: 'addr-018', score: 49, is_probationary_provider: false, technician_count: 4, provider_property_distance_in_miles: 34.9, is_provider_recommended_for_job: false, confidence: ConfidenceLevel.CONFIDENCE_LEVEL_UNSPECIFIED, behavior_labels: [] },
      { provider_id: 'prov-019', provider_name: 'Greater Bloomington Plumbing', provider_address_id: 'addr-019', score: 47, is_probationary_provider: false, technician_count: 6, provider_property_distance_in_miles: 37.2, is_provider_recommended_for_job: false, confidence: ConfidenceLevel.CONFIDENCE_LEVEL_UNSPECIFIED, behavior_labels: [] },
      { provider_id: 'prov-020', provider_name: 'Flat Iron Mechanical', provider_address_id: 'addr-020', score: 45, is_probationary_provider: false, technician_count: 3, provider_property_distance_in_miles: 39.8, is_provider_recommended_for_job: false, confidence: ConfidenceLevel.CONFIDENCE_LEVEL_UNSPECIFIED, behavior_labels: [] },
      { provider_id: 'prov-021', provider_name: 'Crossroads Plumbing', provider_address_id: 'addr-021', score: 43, is_probationary_provider: false, technician_count: 5, provider_property_distance_in_miles: 42.1, is_provider_recommended_for_job: false, confidence: ConfidenceLevel.CONFIDENCE_LEVEL_UNSPECIFIED, behavior_labels: [] },
      { provider_id: 'prov-022', provider_name: 'American Plumbing & Heating', provider_address_id: 'addr-022', score: 40, is_probationary_provider: false, technician_count: 7, provider_property_distance_in_miles: 45.0, is_provider_recommended_for_job: false, confidence: ConfidenceLevel.CONFIDENCE_LEVEL_UNSPECIFIED, behavior_labels: [] },
    ]
  ),
  filtration_stats: [
    { reason: 'INSURANCE LAPSED OR MISSING', count: 14 },
    { reason: 'NO ACTIVE PLUMBING LICENSE', count: 8 },
    { reason: 'UNABLE TO MEET SLA', count: 5 },
    { reason: 'CUSTOMER BLOCK ON FILE', count: 2 },
  ],
};

export const MOCK_VERIFY_RESPONSE: WorkVerificationReportV2 = {
  work_id: 'DEMO_WV_PLUMBING_WATER_HEATER_01',
  report_id: 'rpt-abc123',
  verification_report_status: VerificationReportStatus.VERIFICATION_REPORT_STATUS_COMPLETED,
  work_actions: [
    {
      action_id: 'wa-000',
      type: WorkActionType.WORK_ACTION_TYPE_DOCUMENTATION,
      category: WorkActionCategory.WORK_ACTION_CATEGORY_OTHERS,
      priority: WorkActionPriority.WORK_ACTION_PRIORITY_HIGH,
      description: 'Identify yourself to site management at front desk, sign in, and be escorted to utility room',
      status: WorkActionStatus.WORK_ACTION_STATUS_COMPLETE,
      status_update_context: {
        rationale: 'Provider checked in at front desk and was escorted to utility room per special instructions.',
        evidences: [],
      },
    },
    {
      action_id: 'wa-001a',
      type: WorkActionType.WORK_ACTION_TYPE_DOCUMENTATION,
      category: WorkActionCategory.WORK_ACTION_CATEGORY_INSPECTION,
      priority: WorkActionPriority.WORK_ACTION_PRIORITY_HIGH,
      description: 'Take before photos of water heater unit, pilot assembly, and surrounding area',
      status: WorkActionStatus.WORK_ACTION_STATUS_COMPLETE,
      status_update_context: {
        rationale: 'Before photos submitted showing water heater unit with dark pilot window confirming pre-service condition.',
        evidences: [
          {
            id: 'ev-img-before-0',
            type: EvidenceType.EVIDENCE_TYPE_BEFORE_IMAGES,
            visit_id: 'visit-001',
            rationale: 'Before images document pre-service state of unit and pilot assembly.',
          },
        ],
      },
    },
    {
      action_id: 'wa-001',
      type: WorkActionType.WORK_ACTION_TYPE_ESSENTIAL,
      category: WorkActionCategory.WORK_ACTION_CATEGORY_INSPECTION,
      priority: WorkActionPriority.WORK_ACTION_PRIORITY_HIGH,
      description: 'Inspect pilot assembly and thermocouple for damage or buildup',
      status: WorkActionStatus.WORK_ACTION_STATUS_COMPLETE,
      status_update_context: {
        rationale:
          'Before photo shows pilot assembly with visible soot buildup. After photo confirms cleaned assembly.',
        evidences: [
          {
            id: 'ev-img-before-1',
            type: EvidenceType.EVIDENCE_TYPE_BEFORE_IMAGES,
            visit_id: 'visit-001',
            rationale: 'Before image shows pilot assembly condition prior to cleaning.',
          },
        ],
      },
    },
    {
      action_id: 'wa-002',
      type: WorkActionType.WORK_ACTION_TYPE_ESSENTIAL,
      category: WorkActionCategory.WORK_ACTION_CATEGORY_CLEANING,
      priority: WorkActionPriority.WORK_ACTION_PRIORITY_HIGH,
      description: 'Clean pilot orifice and thermocouple',
      status: WorkActionStatus.WORK_ACTION_STATUS_COMPLETE,
      status_update_context: {
        rationale: 'During photo shows technician actively cleaning pilot components.',
        evidences: [
          {
            id: 'ev-img-during-1',
            type: EvidenceType.EVIDENCE_TYPE_DURING_IMAGES,
            visit_id: 'visit-001',
            rationale: 'During image documents cleaning procedure in progress.',
          },
        ],
      },
    },
    {
      action_id: 'wa-003',
      type: WorkActionType.WORK_ACTION_TYPE_ESSENTIAL,
      category: WorkActionCategory.WORK_ACTION_CATEGORY_REPAIR,
      priority: WorkActionPriority.WORK_ACTION_PRIORITY_HIGH,
      description: 'Re-ignite pilot light per manufacturer procedure and verify stable flame',
      status: WorkActionStatus.WORK_ACTION_STATUS_COMPLETE,
      status_update_context: {
        rationale:
          'After photo clearly shows pilot assembly with visible steady blue flame confirming successful re-ignition.',
        evidences: [
          {
            id: 'ev-img-after-1',
            type: EvidenceType.EVIDENCE_TYPE_AFTER_IMAGES,
            visit_id: 'visit-001',
            rationale: 'After image shows burning pilot flame confirming successful re-ignition.',
          },
        ],
      },
    },
    {
      action_id: 'wa-004',
      type: WorkActionType.WORK_ACTION_TYPE_AUXILIARY,
      category: WorkActionCategory.WORK_ACTION_CATEGORY_TESTING,
      priority: WorkActionPriority.WORK_ACTION_PRIORITY_MEDIUM,
      description: 'Test hot water supply at nearest fixture and verify temperature recovery',
      status: WorkActionStatus.WORK_ACTION_STATUS_COMPLETE,
      status_update_context: {
        rationale:
          'After photo shows technician running faucet with steam visible confirming hot water restored.',
        evidences: [
          {
            id: 'ev-img-after-2',
            type: EvidenceType.EVIDENCE_TYPE_AFTER_IMAGES,
            visit_id: 'visit-001',
            rationale: 'After image shows hot water flow test at sink fixture.',
          },
        ],
      },
    },
    {
      action_id: 'wa-005',
      type: WorkActionType.WORK_ACTION_TYPE_DOCUMENTATION,
      category: WorkActionCategory.WORK_ACTION_CATEGORY_INSPECTION,
      priority: WorkActionPriority.WORK_ACTION_PRIORITY_HIGH,
      description: 'Take after photos of pilot assembly with flame visible, water heater controls, and faucet running hot water',
      status: WorkActionStatus.WORK_ACTION_STATUS_COMPLETE,
      status_update_context: {
        rationale: 'After photos show burning pilot flame and running hot water at faucet confirming service restoration.',
        evidences: [
          {
            id: 'ev-img-after-3',
            type: EvidenceType.EVIDENCE_TYPE_AFTER_IMAGES,
            visit_id: 'visit-001',
            rationale: 'After images document full service restoration with flame and hot water.',
          },
        ],
      },
    },
    {
      action_id: 'wa-006',
      type: WorkActionType.WORK_ACTION_TYPE_DOCUMENTATION,
      category: WorkActionCategory.WORK_ACTION_CATEGORY_OTHERS,
      priority: WorkActionPriority.WORK_ACTION_PRIORITY_HIGH,
      description: 'Clean up work area, return utility room to pre-service condition, and obtain site manager signature',
      status: WorkActionStatus.WORK_ACTION_STATUS_COMPLETE,
      status_update_context: {
        rationale: 'Work area cleaned and site manager sign-off obtained before provider departure.',
        evidences: [],
      },
    },
  ],
  image_analyses: [
    { image_id: 'img-before-1', analysis: 'Pilot assembly with soot buildup visible', evidence_type: EvidenceType.EVIDENCE_TYPE_BEFORE_IMAGES },
    { image_id: 'img-before-2', analysis: 'Water heater unit from front, pilot window dark', evidence_type: EvidenceType.EVIDENCE_TYPE_BEFORE_IMAGES },
    { image_id: 'img-before-3', analysis: 'Utility room context shot showing heater location', evidence_type: EvidenceType.EVIDENCE_TYPE_BEFORE_IMAGES },
    { image_id: 'img-during-1', analysis: 'Technician cleaning pilot orifice with brush', evidence_type: EvidenceType.EVIDENCE_TYPE_DURING_IMAGES },
    { image_id: 'img-during-2', analysis: 'Close-up of thermocouple being cleaned', evidence_type: EvidenceType.EVIDENCE_TYPE_DURING_IMAGES },
    { image_id: 'img-during-3', analysis: 'Technician following ignition procedure at controls', evidence_type: EvidenceType.EVIDENCE_TYPE_DURING_IMAGES },
    { image_id: 'img-after-1', analysis: 'Pilot assembly with steady blue flame visible', evidence_type: EvidenceType.EVIDENCE_TYPE_AFTER_IMAGES },
    { image_id: 'img-after-2', analysis: 'Hot water running at faucet, steam visible', evidence_type: EvidenceType.EVIDENCE_TYPE_AFTER_IMAGES },
    { image_id: 'img-after-3', analysis: 'Water heater controls showing proper operating temperature', evidence_type: EvidenceType.EVIDENCE_TYPE_AFTER_IMAGES },
  ],
  verification_results: {
    complete_reason:
      'All essential tasks completed and documented with photographic evidence across all visit windows.',
    work_completion_status: WorkCompletionStatus.WORK_COMPLETION_STATUS_COMPLETE,
    work_completion_confidence: ConfidenceLevel.CONFIDENCE_LEVEL_HIGH,
    labor_hours_assessment: {
      is_appropriate: true,
      confidence: ConfidenceLevel.CONFIDENCE_LEVEL_HIGH,
      labor_prediction_id: 'labor-pred-001',
    },
    work_verification_rationale:
      'The hot water heater pilot was successfully re-ignited as evidenced by the before and after photos showing the pilot assembly with visible flame in the after photos. All required tasks were completed and documented with sufficient photographic evidence. Time on-site of 47 minutes is appropriate for pilot inspection, cleaning, and re-ignition work at this scope level.',
  },
};

// ─── HVAC Not Cooling ─────────────────────────────────────────────────────────

const HVAC_QUALIFY: PredictionResponse = {
  is_recall: false,
  is_recall_v2: false,
  is_estimate: false,
  is_parts_and_order: false,
  service_type_id: 'svc-type-hvac-not-cooling',
  service_line_id: 'svc-line-hvac',
  is_project_work: false,
  enriched_ticket_scope:
    'Commercial HVAC unit not cooling at retail pharmacy. Interior temperature elevated. Requires refrigerant check, filter inspection, and system diagnostic.',
  work_scope:
    'Perform full system diagnostic on rooftop HVAC unit. Inspect and replace air filter. Check refrigerant pressure and look for visible leaks. Inspect evaporator and condenser coils. Test thermostat calibration and verify supply air temperature at registers. Document findings and restore cooling.',
  work_type: 'REPAIR',
  asset: 'Rooftop HVAC Unit',
  location: 'Rooftop / Mechanical Area',
  special_instructions:
    'Rooftop access requires key from store manager. Safety harness required per site policy.',
  recommendation_id: 'rec-hvac-001',
  work_complexity: 'SIMPLE',
};

const HVAC_WORK_ACTIONS: WorkAction[] = [
  {
    action_id: 'wa-hvac-000',
    type: WorkActionType.WORK_ACTION_TYPE_DOCUMENTATION,
    category: WorkActionCategory.WORK_ACTION_CATEGORY_OTHERS,
    priority: WorkActionPriority.WORK_ACTION_PRIORITY_HIGH,
    description: 'Check in with store manager, obtain rooftop access key and safety harness',
    status: WorkActionStatus.WORK_ACTION_STATUS_TODO,
    creation_context: { rationale: 'Rooftop access requires manager key and site safety harness per special instructions.', evidences: [] },
  },
  {
    action_id: 'wa-hvac-001a',
    type: WorkActionType.WORK_ACTION_TYPE_DOCUMENTATION,
    category: WorkActionCategory.WORK_ACTION_CATEGORY_INSPECTION,
    priority: WorkActionPriority.WORK_ACTION_PRIORITY_HIGH,
    description: 'Take before photos of rooftop unit, thermostat display showing warm temperature, and interior conditions',
    status: WorkActionStatus.WORK_ACTION_STATUS_TODO,
    creation_context: { rationale: 'Before photos establish baseline condition for quality verification.', evidences: [] },
  },
  {
    action_id: 'wa-hvac-001',
    type: WorkActionType.WORK_ACTION_TYPE_ESSENTIAL,
    category: WorkActionCategory.WORK_ACTION_CATEGORY_INSPECTION,
    priority: WorkActionPriority.WORK_ACTION_PRIORITY_HIGH,
    description: 'Inspect and replace air filter — document filter condition and MERV rating',
    status: WorkActionStatus.WORK_ACTION_STATUS_TODO,
    creation_context: { rationale: 'Clogged filter is a primary cause of reduced cooling. Must be inspected and replaced.', evidences: [] },
  },
  {
    action_id: 'wa-hvac-002',
    type: WorkActionType.WORK_ACTION_TYPE_ESSENTIAL,
    category: WorkActionCategory.WORK_ACTION_CATEGORY_INSPECTION,
    priority: WorkActionPriority.WORK_ACTION_PRIORITY_HIGH,
    description: 'Check refrigerant pressure at service ports — record high-side and low-side readings',
    status: WorkActionStatus.WORK_ACTION_STATUS_TODO,
    creation_context: { rationale: 'Low refrigerant is a critical indicator of leak or charge loss causing cooling failure.', evidences: [] },
  },
  {
    action_id: 'wa-hvac-003',
    type: WorkActionType.WORK_ACTION_TYPE_ESSENTIAL,
    category: WorkActionCategory.WORK_ACTION_CATEGORY_INSPECTION,
    priority: WorkActionPriority.WORK_ACTION_PRIORITY_HIGH,
    description: 'Inspect evaporator coil and condenser coil for blockage, frost, or damage',
    status: WorkActionStatus.WORK_ACTION_STATUS_TODO,
    creation_context: { rationale: 'Coil condition directly impacts cooling efficiency and must be verified during diagnostic.', evidences: [] },
  },
  {
    action_id: 'wa-hvac-004',
    type: WorkActionType.WORK_ACTION_TYPE_ESSENTIAL,
    category: WorkActionCategory.WORK_ACTION_CATEGORY_REPAIR,
    priority: WorkActionPriority.WORK_ACTION_PRIORITY_HIGH,
    description: 'Test thermostat calibration and confirm setpoint vs. actual temperature delta',
    status: WorkActionStatus.WORK_ACTION_STATUS_TODO,
    creation_context: { rationale: 'Thermostat miscalibration can prevent cooling even when system is mechanically functional.', evidences: [] },
  },
  {
    action_id: 'wa-hvac-005',
    type: WorkActionType.WORK_ACTION_TYPE_AUXILIARY,
    category: WorkActionCategory.WORK_ACTION_CATEGORY_TESTING,
    priority: WorkActionPriority.WORK_ACTION_PRIORITY_MEDIUM,
    description: 'Verify supply air temperature at registers after repair — confirm cooling restored to 72°F or below',
    status: WorkActionStatus.WORK_ACTION_STATUS_TODO,
    creation_context: { rationale: 'End-to-end functional test confirms cooling is fully restored at delivery points.', evidences: [] },
  },
  {
    action_id: 'wa-hvac-006',
    type: WorkActionType.WORK_ACTION_TYPE_DOCUMENTATION,
    category: WorkActionCategory.WORK_ACTION_CATEGORY_OTHERS,
    priority: WorkActionPriority.WORK_ACTION_PRIORITY_HIGH,
    description: 'Take after photos showing thermostat at setpoint, supply air temp reading, and unit operational — obtain manager sign-off',
    status: WorkActionStatus.WORK_ACTION_STATUS_TODO,
    creation_context: { rationale: 'After photos and manager sign-off close the service loop and confirm cooling restoration.', evidences: [] },
  },
];

const HVAC_MATCH: MatchResponse = {
  total_matched: 47,
  providers: makeProviders(
    [
      {
        provider_id: 'hvac-prov-001',
        provider_name: 'Austin HVAC Solutions',
        provider_address_id: 'hvac-addr-001',
        score: 91,
        is_probationary_provider: false,
        technician_count: 10,
        provider_property_distance_in_miles: 5.1,
        tags: [],
        is_provider_recommended_for_job: true,
        ai_rationale: 'Austin HVAC Solutions has serviced 18 pharmacy HVAC units with a 98% first-time completion rate. Strong refrigerant certification and same-day availability.',
        confidence: ConfidenceLevel.CONFIDENCE_LEVEL_HIGH,
        behavior_labels: ['property_veteran', 'reliable_acceptor'],
        speed_score: 88,
        quality_score: 92,
        cost_score: 85,
        rating: 4.8,
        review_count: 512,
        jobs_completed: 1820,
        scorecard_details: {
          speed: { overall: 88, on_time_arrival: 90, time_to_work_done: 86 },
          quality: { overall: 92, first_time_complete: 89, defect_free_jobs: 97, app_compliance: 91 },
          cost: { overall: 85, used_under_nte: 78, dispute_free: 94 },
        },
      },
      {
        provider_id: 'hvac-prov-002',
        provider_name: 'Texas Comfort Systems',
        provider_address_id: 'hvac-addr-002',
        score: 84,
        is_probationary_provider: false,
        technician_count: 15,
        provider_property_distance_in_miles: 7.8,
        tags: [],
        is_provider_recommended_for_job: true,
        ai_rationale: 'Texas Comfort Systems offers strong regional HVAC coverage with NATE-certified technicians and an excellent refrigerant compliance record.',
        confidence: ConfidenceLevel.CONFIDENCE_LEVEL_HIGH,
        behavior_labels: ['customer_veteran', 'high_performance_score'],
        speed_score: 82,
        quality_score: 87,
        cost_score: 88,
        rating: 4.6,
        review_count: 348,
        jobs_completed: 1204,
        scorecard_details: {
          speed: { overall: 82, on_time_arrival: 80, time_to_work_done: 85 },
          quality: { overall: 87, first_time_complete: 84, defect_free_jobs: 92, app_compliance: 88 },
          cost: { overall: 88, used_under_nte: 85, dispute_free: 92 },
        },
      },
      {
        provider_id: 'hvac-prov-003',
        provider_name: 'Lone Star Mechanical',
        provider_address_id: 'hvac-addr-003',
        score: 77,
        is_probationary_provider: false,
        technician_count: 8,
        provider_property_distance_in_miles: 10.2,
        tags: [],
        is_provider_recommended_for_job: true,
        ai_rationale: 'Solid HVAC contractor with rooftop unit specialization. Good on-time arrival record across the Austin market.',
        confidence: ConfidenceLevel.CONFIDENCE_LEVEL_MEDIUM,
        behavior_labels: ['on_time_arrival'],
        speed_score: 75,
        quality_score: 82,
        cost_score: 80,
        rating: 4.4,
        review_count: 198,
        jobs_completed: 672,
        scorecard_details: {
          speed: { overall: 75, on_time_arrival: 82, time_to_work_done: 72 },
          quality: { overall: 82, first_time_complete: 78, defect_free_jobs: 89, app_compliance: 80 },
          cost: { overall: 80, used_under_nte: 74, dispute_free: 88 },
        },
      },
    ],
    [
      { provider_id: 'hvac-prov-004', provider_name: 'Capital HVAC Services', provider_address_id: 'hvac-addr-004', score: 74, is_probationary_provider: false, technician_count: 6, provider_property_distance_in_miles: 12.3, is_provider_recommended_for_job: false, confidence: ConfidenceLevel.CONFIDENCE_LEVEL_UNSPECIFIED, behavior_labels: [] },
      { provider_id: 'hvac-prov-005', provider_name: 'Hill Country Air', provider_address_id: 'hvac-addr-005', score: 71, is_probationary_provider: false, technician_count: 9, provider_property_distance_in_miles: 13.8, is_provider_recommended_for_job: false, confidence: ConfidenceLevel.CONFIDENCE_LEVEL_UNSPECIFIED, behavior_labels: ['reliable_acceptor'] },
      { provider_id: 'hvac-prov-006', provider_name: 'Central Texas Cooling', provider_address_id: 'hvac-addr-006', score: 69, is_probationary_provider: false, technician_count: 5, provider_property_distance_in_miles: 15.2, is_provider_recommended_for_job: false, confidence: ConfidenceLevel.CONFIDENCE_LEVEL_UNSPECIFIED, behavior_labels: [] },
      { provider_id: 'hvac-prov-007', provider_name: 'Lakeway HVAC Co.', provider_address_id: 'hvac-addr-007', score: 67, is_probationary_provider: false, technician_count: 4, provider_property_distance_in_miles: 16.9, is_provider_recommended_for_job: false, confidence: ConfidenceLevel.CONFIDENCE_LEVEL_UNSPECIFIED, behavior_labels: [] },
      { provider_id: 'hvac-prov-008', provider_name: 'Pflugerville Air Services', provider_address_id: 'hvac-addr-008', score: 65, is_probationary_provider: false, technician_count: 7, provider_property_distance_in_miles: 18.4, is_provider_recommended_for_job: false, confidence: ConfidenceLevel.CONFIDENCE_LEVEL_UNSPECIFIED, behavior_labels: [] },
      { provider_id: 'hvac-prov-009', provider_name: 'Round Rock Mechanical', provider_address_id: 'hvac-addr-009', score: 63, is_probationary_provider: false, technician_count: 6, provider_property_distance_in_miles: 20.0, is_provider_recommended_for_job: false, confidence: ConfidenceLevel.CONFIDENCE_LEVEL_UNSPECIFIED, behavior_labels: [] },
      { provider_id: 'hvac-prov-010', provider_name: 'Cedar Park HVAC', provider_address_id: 'hvac-addr-010', score: 61, is_probationary_provider: false, technician_count: 5, provider_property_distance_in_miles: 21.6, is_provider_recommended_for_job: false, confidence: ConfidenceLevel.CONFIDENCE_LEVEL_UNSPECIFIED, behavior_labels: [] },
      { provider_id: 'hvac-prov-011', provider_name: 'Leander Air Solutions', provider_address_id: 'hvac-addr-011', score: 59, is_probationary_provider: false, technician_count: 4, provider_property_distance_in_miles: 23.5, is_provider_recommended_for_job: false, confidence: ConfidenceLevel.CONFIDENCE_LEVEL_UNSPECIFIED, behavior_labels: [] },
      { provider_id: 'hvac-prov-012', provider_name: 'Georgetown Cooling Group', provider_address_id: 'hvac-addr-012', score: 57, is_probationary_provider: false, technician_count: 8, provider_property_distance_in_miles: 25.8, is_provider_recommended_for_job: false, confidence: ConfidenceLevel.CONFIDENCE_LEVEL_UNSPECIFIED, behavior_labels: [] },
      { provider_id: 'hvac-prov-013', provider_name: 'Buda Mechanical Services', provider_address_id: 'hvac-addr-013', score: 55, is_probationary_provider: false, technician_count: 5, provider_property_distance_in_miles: 27.1, is_provider_recommended_for_job: false, confidence: ConfidenceLevel.CONFIDENCE_LEVEL_UNSPECIFIED, behavior_labels: [] },
      { provider_id: 'hvac-prov-014', provider_name: 'Kyle HVAC Pros', provider_address_id: 'hvac-addr-014', score: 53, is_probationary_provider: false, technician_count: 6, provider_property_distance_in_miles: 29.4, is_provider_recommended_for_job: false, confidence: ConfidenceLevel.CONFIDENCE_LEVEL_UNSPECIFIED, behavior_labels: [] },
      { provider_id: 'hvac-prov-015', provider_name: 'San Marcos Air Works', provider_address_id: 'hvac-addr-015', score: 51, is_probationary_provider: false, technician_count: 7, provider_property_distance_in_miles: 31.7, is_provider_recommended_for_job: false, confidence: ConfidenceLevel.CONFIDENCE_LEVEL_UNSPECIFIED, behavior_labels: [] },
      { provider_id: 'hvac-prov-016', provider_name: 'Wimberley Cooling', provider_address_id: 'hvac-addr-016', score: 49, is_probationary_provider: false, technician_count: 3, provider_property_distance_in_miles: 33.9, is_provider_recommended_for_job: false, confidence: ConfidenceLevel.CONFIDENCE_LEVEL_UNSPECIFIED, behavior_labels: [] },
      { provider_id: 'hvac-prov-017', provider_name: 'Bastrop HVAC Group', provider_address_id: 'hvac-addr-017', score: 47, is_probationary_provider: false, technician_count: 5, provider_property_distance_in_miles: 36.2, is_provider_recommended_for_job: false, confidence: ConfidenceLevel.CONFIDENCE_LEVEL_UNSPECIFIED, behavior_labels: [] },
      { provider_id: 'hvac-prov-018', provider_name: 'Elgin Mechanical', provider_address_id: 'hvac-addr-018', score: 45, is_probationary_provider: false, technician_count: 4, provider_property_distance_in_miles: 38.5, is_provider_recommended_for_job: false, confidence: ConfidenceLevel.CONFIDENCE_LEVEL_UNSPECIFIED, behavior_labels: [] },
      { provider_id: 'hvac-prov-019', provider_name: 'Taylor Air Services', provider_address_id: 'hvac-addr-019', score: 43, is_probationary_provider: false, technician_count: 6, provider_property_distance_in_miles: 41.0, is_provider_recommended_for_job: false, confidence: ConfidenceLevel.CONFIDENCE_LEVEL_UNSPECIFIED, behavior_labels: [] },
      { provider_id: 'hvac-prov-020', provider_name: 'Hutto HVAC Solutions', provider_address_id: 'hvac-addr-020', score: 41, is_probationary_provider: false, technician_count: 5, provider_property_distance_in_miles: 43.3, is_provider_recommended_for_job: false, confidence: ConfidenceLevel.CONFIDENCE_LEVEL_UNSPECIFIED, behavior_labels: [] },
      { provider_id: 'hvac-prov-021', provider_name: 'Manor Cooling & Heating', provider_address_id: 'hvac-addr-021', score: 40, is_probationary_provider: false, technician_count: 4, provider_property_distance_in_miles: 45.0, is_provider_recommended_for_job: false, confidence: ConfidenceLevel.CONFIDENCE_LEVEL_UNSPECIFIED, behavior_labels: [] },
    ]
  ),
  filtration_stats: [
    { reason: 'INSURANCE LAPSED OR MISSING', count: 9 },
    { reason: 'NO ACTIVE HVAC LICENSE', count: 5 },
    { reason: 'UNABLE TO MEET SLA', count: 6 },
    { reason: 'CUSTOMER BLOCK ON FILE', count: 3 },
  ],
};

const HVAC_VERIFY: WorkVerificationReportV2 = {
  work_id: 'DEMO_WV_HVAC_NOT_COOLING_01',
  report_id: 'rpt-hvac-001',
  verification_report_status: VerificationReportStatus.VERIFICATION_REPORT_STATUS_COMPLETED,
  work_actions: [
    {
      action_id: 'wa-hvac-000',
      type: WorkActionType.WORK_ACTION_TYPE_DOCUMENTATION,
      category: WorkActionCategory.WORK_ACTION_CATEGORY_OTHERS,
      priority: WorkActionPriority.WORK_ACTION_PRIORITY_HIGH,
      description: 'Check in with store manager, obtain rooftop access key and safety harness',
      status: WorkActionStatus.WORK_ACTION_STATUS_COMPLETE,
      status_update_context: { rationale: 'Provider checked in with manager and obtained rooftop access key and required safety harness.', evidences: [] },
    },
    {
      action_id: 'wa-hvac-001a',
      type: WorkActionType.WORK_ACTION_TYPE_DOCUMENTATION,
      category: WorkActionCategory.WORK_ACTION_CATEGORY_INSPECTION,
      priority: WorkActionPriority.WORK_ACTION_PRIORITY_HIGH,
      description: 'Take before photos of rooftop unit, thermostat display, and interior conditions',
      status: WorkActionStatus.WORK_ACTION_STATUS_COMPLETE,
      status_update_context: { rationale: 'Before photos submitted showing thermostat reading 82°F and rooftop unit condition.', evidences: [{ id: 'ev-hvac-before-1', type: EvidenceType.EVIDENCE_TYPE_BEFORE_IMAGES, visit_id: 'visit-hvac-001', rationale: 'Before images document warm interior and unit pre-service state.' }] },
    },
    {
      action_id: 'wa-hvac-001',
      type: WorkActionType.WORK_ACTION_TYPE_ESSENTIAL,
      category: WorkActionCategory.WORK_ACTION_CATEGORY_INSPECTION,
      priority: WorkActionPriority.WORK_ACTION_PRIORITY_HIGH,
      description: 'Inspect and replace air filter',
      status: WorkActionStatus.WORK_ACTION_STATUS_COMPLETE,
      status_update_context: { rationale: 'MERV-8 filter replaced. During photo shows heavily loaded filter removed and new filter installed.', evidences: [{ id: 'ev-hvac-during-1', type: EvidenceType.EVIDENCE_TYPE_DURING_IMAGES, visit_id: 'visit-hvac-001', rationale: 'During image shows clogged filter replacement in progress.' }] },
    },
    {
      action_id: 'wa-hvac-002',
      type: WorkActionType.WORK_ACTION_TYPE_ESSENTIAL,
      category: WorkActionCategory.WORK_ACTION_CATEGORY_INSPECTION,
      priority: WorkActionPriority.WORK_ACTION_PRIORITY_HIGH,
      description: 'Check refrigerant pressure at service ports',
      status: WorkActionStatus.WORK_ACTION_STATUS_COMPLETE,
      status_update_context: { rationale: 'Refrigerant pressures recorded: high-side 225 PSI, low-side 68 PSI. Readings within normal range for R-410A.', evidences: [] },
    },
    {
      action_id: 'wa-hvac-003',
      type: WorkActionType.WORK_ACTION_TYPE_ESSENTIAL,
      category: WorkActionCategory.WORK_ACTION_CATEGORY_INSPECTION,
      priority: WorkActionPriority.WORK_ACTION_PRIORITY_HIGH,
      description: 'Inspect evaporator and condenser coils',
      status: WorkActionStatus.WORK_ACTION_STATUS_COMPLETE,
      status_update_context: { rationale: 'Both coils inspected. Condenser coil had light debris buildup, cleaned with coil brush. No frost or damage found.', evidences: [] },
    },
    {
      action_id: 'wa-hvac-006',
      type: WorkActionType.WORK_ACTION_TYPE_DOCUMENTATION,
      category: WorkActionCategory.WORK_ACTION_CATEGORY_OTHERS,
      priority: WorkActionPriority.WORK_ACTION_PRIORITY_HIGH,
      description: 'After photos showing thermostat at setpoint and unit operational — obtain manager sign-off',
      status: WorkActionStatus.WORK_ACTION_STATUS_COMPLETE,
      status_update_context: { rationale: 'After photos show thermostat reading 70°F at setpoint. Manager sign-off obtained. Cooling fully restored.', evidences: [{ id: 'ev-hvac-after-1', type: EvidenceType.EVIDENCE_TYPE_AFTER_IMAGES, visit_id: 'visit-hvac-001', rationale: 'After images confirm cooling restored and thermostat at setpoint.' }] },
    },
  ],
  image_analyses: [
    { image_id: 'img-hvac-before-1', analysis: 'Thermostat display showing 82°F interior temperature', evidence_type: EvidenceType.EVIDENCE_TYPE_BEFORE_IMAGES },
    { image_id: 'img-hvac-before-2', analysis: 'Rooftop HVAC unit exterior in pre-service condition', evidence_type: EvidenceType.EVIDENCE_TYPE_BEFORE_IMAGES },
    { image_id: 'img-hvac-during-1', analysis: 'Heavily loaded MERV-8 filter removed from housing', evidence_type: EvidenceType.EVIDENCE_TYPE_DURING_IMAGES },
    { image_id: 'img-hvac-during-2', analysis: 'New filter installed, technician sealing filter access panel', evidence_type: EvidenceType.EVIDENCE_TYPE_DURING_IMAGES },
    { image_id: 'img-hvac-after-1', analysis: 'Thermostat display showing 70°F at setpoint', evidence_type: EvidenceType.EVIDENCE_TYPE_AFTER_IMAGES },
    { image_id: 'img-hvac-after-2', analysis: 'Supply register thermometer confirming 68°F supply air', evidence_type: EvidenceType.EVIDENCE_TYPE_AFTER_IMAGES },
  ],
  verification_results: {
    complete_reason: 'All essential HVAC tasks completed. Cooling restored and documented with photographic evidence.',
    work_completion_status: WorkCompletionStatus.WORK_COMPLETION_STATUS_COMPLETE,
    work_completion_confidence: ConfidenceLevel.CONFIDENCE_LEVEL_HIGH,
    labor_hours_assessment: { is_appropriate: true, confidence: ConfidenceLevel.CONFIDENCE_LEVEL_HIGH, labor_prediction_id: 'labor-pred-hvac-001' },
    work_verification_rationale: 'The HVAC unit was restored to cooling operation. Filter replacement resolved the primary issue. Refrigerant pressures confirmed within normal range. Before and after photos document temperature drop from 82°F to 70°F confirming full cooling restoration.',
  },
};

// ─── Ceiling Tile Damage ──────────────────────────────────────────────────────

const CEILING_QUALIFY: PredictionResponse = {
  is_recall: false,
  is_recall_v2: false,
  is_estimate: false,
  is_parts_and_order: false,
  service_type_id: 'svc-type-ceiling-tile-damage',
  service_line_id: 'svc-line-general-maintenance',
  is_project_work: false,
  enriched_ticket_scope:
    'Multiple ceiling tiles sagging and damaged in back stockroom at hardware store. Possible water intrusion from roof or plumbing above.',
  work_scope:
    'Assess extent of ceiling tile damage and identify water source. Remove damaged tiles and inspect above ceiling for active leaks. Check for mold or mildew. Replace all damaged tiles with matching 2x4 acoustic tile. Ensure proper seating in grid system. Document findings for potential follow-up roof repair.',
  work_type: 'REPAIR',
  asset: 'Drop Ceiling / Acoustic Tiles',
  location: 'Back Stockroom',
  special_instructions:
    'Stockroom access through loading dock. Coordinate with stock manager for aisle clearance.',
  recommendation_id: 'rec-ceiling-001',
  work_complexity: 'SIMPLE',
};

const CEILING_WORK_ACTIONS: WorkAction[] = [
  {
    action_id: 'wa-ct-000',
    type: WorkActionType.WORK_ACTION_TYPE_DOCUMENTATION,
    category: WorkActionCategory.WORK_ACTION_CATEGORY_OTHERS,
    priority: WorkActionPriority.WORK_ACTION_PRIORITY_HIGH,
    description: 'Check in at loading dock, coordinate with stock manager to clear aisle access below work area',
    status: WorkActionStatus.WORK_ACTION_STATUS_TODO,
    creation_context: { rationale: 'Loading dock access and aisle clearance required per special instructions before work begins.', evidences: [] },
  },
  {
    action_id: 'wa-ct-001a',
    type: WorkActionType.WORK_ACTION_TYPE_DOCUMENTATION,
    category: WorkActionCategory.WORK_ACTION_CATEGORY_INSPECTION,
    priority: WorkActionPriority.WORK_ACTION_PRIORITY_HIGH,
    description: 'Take before photos of all damaged tiles, grid system, and any visible water staining',
    status: WorkActionStatus.WORK_ACTION_STATUS_TODO,
    creation_context: { rationale: 'Before photos document the extent of damage and any water staining for insurance and follow-up purposes.', evidences: [] },
  },
  {
    action_id: 'wa-ct-001',
    type: WorkActionType.WORK_ACTION_TYPE_ESSENTIAL,
    category: WorkActionCategory.WORK_ACTION_CATEGORY_INSPECTION,
    priority: WorkActionPriority.WORK_ACTION_PRIORITY_HIGH,
    description: 'Inspect and count all damaged or sagging tiles — record exact count and grid positions',
    status: WorkActionStatus.WORK_ACTION_STATUS_TODO,
    creation_context: { rationale: 'Full inventory of damaged tiles required to confirm materials needed and scope of replacement work.', evidences: [] },
  },
  {
    action_id: 'wa-ct-002',
    type: WorkActionType.WORK_ACTION_TYPE_ESSENTIAL,
    category: WorkActionCategory.WORK_ACTION_CATEGORY_INSPECTION,
    priority: WorkActionPriority.WORK_ACTION_PRIORITY_HIGH,
    description: 'Remove damaged tiles and inspect above-ceiling space for active leak source, mold, or structural damage',
    status: WorkActionStatus.WORK_ACTION_STATUS_TODO,
    creation_context: { rationale: 'Above-ceiling inspection is critical to identify and document the source of water intrusion.', evidences: [] },
  },
  {
    action_id: 'wa-ct-003',
    type: WorkActionType.WORK_ACTION_TYPE_ESSENTIAL,
    category: WorkActionCategory.WORK_ACTION_CATEGORY_REPLACEMENT,
    priority: WorkActionPriority.WORK_ACTION_PRIORITY_HIGH,
    description: 'Install matching 2x4 acoustic replacement tiles — ensure proper fit in T-bar grid system',
    status: WorkActionStatus.WORK_ACTION_STATUS_TODO,
    creation_context: { rationale: 'Matching tile replacement restores ceiling appearance and acoustics. Proper T-bar seating prevents future sagging.', evidences: [] },
  },
  {
    action_id: 'wa-ct-004',
    type: WorkActionType.WORK_ACTION_TYPE_AUXILIARY,
    category: WorkActionCategory.WORK_ACTION_CATEGORY_INSPECTION,
    priority: WorkActionPriority.WORK_ACTION_PRIORITY_MEDIUM,
    description: 'Check adjacent tiles for moisture damage — replace any borderline tiles proactively',
    status: WorkActionStatus.WORK_ACTION_STATUS_TODO,
    creation_context: { rationale: 'Adjacent tiles may have absorbed moisture and could fail soon. Proactive replacement avoids callback.', evidences: [] },
  },
  {
    action_id: 'wa-ct-005',
    type: WorkActionType.WORK_ACTION_TYPE_DOCUMENTATION,
    category: WorkActionCategory.WORK_ACTION_CATEGORY_OTHERS,
    priority: WorkActionPriority.WORK_ACTION_PRIORITY_HIGH,
    description: 'Take after photos of completed ceiling area showing new tiles installed flush with grid — obtain stock manager sign-off',
    status: WorkActionStatus.WORK_ACTION_STATUS_TODO,
    creation_context: { rationale: 'After photos confirm tile replacement quality and manager sign-off closes the service record.', evidences: [] },
  },
];

const CEILING_MATCH: MatchResponse = {
  total_matched: 38,
  providers: makeProviders(
    [
      {
        provider_id: 'ct-prov-001',
        provider_name: 'Memphis Facilities Group',
        provider_address_id: 'ct-addr-001',
        score: 88,
        is_probationary_provider: false,
        technician_count: 12,
        provider_property_distance_in_miles: 4.3,
        tags: [],
        is_provider_recommended_for_job: true,
        ai_rationale: 'Memphis Facilities Group has extensive retail maintenance history including drop ceiling repair at hardware and home improvement locations. Excellent first-time completion rate.',
        confidence: ConfidenceLevel.CONFIDENCE_LEVEL_HIGH,
        behavior_labels: ['property_veteran', 'reliable_acceptor'],
        speed_score: 85,
        quality_score: 90,
        cost_score: 82,
        rating: 4.7,
        review_count: 389,
        jobs_completed: 1102,
        scorecard_details: {
          speed: { overall: 85, on_time_arrival: 83, time_to_work_done: 88 },
          quality: { overall: 90, first_time_complete: 87, defect_free_jobs: 94, app_compliance: 90 },
          cost: { overall: 82, used_under_nte: 76, dispute_free: 91 },
        },
      },
      {
        provider_id: 'ct-prov-002',
        provider_name: 'Mid-South Maintenance',
        provider_address_id: 'ct-addr-002',
        score: 81,
        is_probationary_provider: false,
        technician_count: 8,
        provider_property_distance_in_miles: 6.7,
        tags: [],
        is_provider_recommended_for_job: true,
        ai_rationale: 'Strong regional general maintenance contractor with good ceiling tile experience and consistent on-time arrival across the Memphis market.',
        confidence: ConfidenceLevel.CONFIDENCE_LEVEL_HIGH,
        behavior_labels: ['customer_veteran'],
        speed_score: 80,
        quality_score: 84,
        cost_score: 86,
        rating: 4.5,
        review_count: 241,
        jobs_completed: 814,
        scorecard_details: {
          speed: { overall: 80, on_time_arrival: 79, time_to_work_done: 82 },
          quality: { overall: 84, first_time_complete: 81, defect_free_jobs: 90, app_compliance: 84 },
          cost: { overall: 86, used_under_nte: 82, dispute_free: 91 },
        },
      },
      {
        provider_id: 'ct-prov-003',
        provider_name: 'Tennessee Handyman Pro',
        provider_address_id: 'ct-addr-003',
        score: 73,
        is_probationary_provider: false,
        technician_count: 5,
        provider_property_distance_in_miles: 9.1,
        tags: [],
        is_provider_recommended_for_job: true,
        ai_rationale: 'Qualified general maintenance provider with ceiling tile replacement on record. Slightly further but available same day.',
        confidence: ConfidenceLevel.CONFIDENCE_LEVEL_MEDIUM,
        behavior_labels: ['on_time_arrival'],
        speed_score: 72,
        quality_score: 78,
        cost_score: 81,
        rating: 4.2,
        review_count: 156,
        jobs_completed: 487,
        scorecard_details: {
          speed: { overall: 72, on_time_arrival: 78, time_to_work_done: 69 },
          quality: { overall: 78, first_time_complete: 75, defect_free_jobs: 84, app_compliance: 77 },
          cost: { overall: 81, used_under_nte: 77, dispute_free: 87 },
        },
      },
    ],
    [
      { provider_id: 'ct-prov-004', provider_name: 'Shelby County Maintenance', provider_address_id: 'ct-addr-004', score: 70, is_probationary_provider: false, technician_count: 7, provider_property_distance_in_miles: 11.2, is_provider_recommended_for_job: false, confidence: ConfidenceLevel.CONFIDENCE_LEVEL_UNSPECIFIED, behavior_labels: [] },
      { provider_id: 'ct-prov-005', provider_name: 'Germantown Facility Services', provider_address_id: 'ct-addr-005', score: 67, is_probationary_provider: false, technician_count: 5, provider_property_distance_in_miles: 12.8, is_provider_recommended_for_job: false, confidence: ConfidenceLevel.CONFIDENCE_LEVEL_UNSPECIFIED, behavior_labels: [] },
      { provider_id: 'ct-prov-006', provider_name: 'Bartlett Building Maintenance', provider_address_id: 'ct-addr-006', score: 65, is_probationary_provider: false, technician_count: 6, provider_property_distance_in_miles: 14.5, is_provider_recommended_for_job: false, confidence: ConfidenceLevel.CONFIDENCE_LEVEL_UNSPECIFIED, behavior_labels: ['reliable_acceptor'] },
      { provider_id: 'ct-prov-007', provider_name: 'Collierville Handyman', provider_address_id: 'ct-addr-007', score: 63, is_probationary_provider: false, technician_count: 4, provider_property_distance_in_miles: 16.1, is_provider_recommended_for_job: false, confidence: ConfidenceLevel.CONFIDENCE_LEVEL_UNSPECIFIED, behavior_labels: [] },
      { provider_id: 'ct-prov-008', provider_name: 'Cordova Maintenance Group', provider_address_id: 'ct-addr-008', score: 61, is_probationary_provider: false, technician_count: 5, provider_property_distance_in_miles: 17.9, is_provider_recommended_for_job: false, confidence: ConfidenceLevel.CONFIDENCE_LEVEL_UNSPECIFIED, behavior_labels: [] },
      { provider_id: 'ct-prov-009', provider_name: 'East Memphis Facilities', provider_address_id: 'ct-addr-009', score: 59, is_probationary_provider: false, technician_count: 6, provider_property_distance_in_miles: 19.6, is_provider_recommended_for_job: false, confidence: ConfidenceLevel.CONFIDENCE_LEVEL_UNSPECIFIED, behavior_labels: [] },
      { provider_id: 'ct-prov-010', provider_name: 'South Memphis Repair Co.', provider_address_id: 'ct-addr-010', score: 57, is_probationary_provider: false, technician_count: 4, provider_property_distance_in_miles: 21.3, is_provider_recommended_for_job: false, confidence: ConfidenceLevel.CONFIDENCE_LEVEL_UNSPECIFIED, behavior_labels: [] },
      { provider_id: 'ct-prov-011', provider_name: 'Whitehaven Maintenance', provider_address_id: 'ct-addr-011', score: 55, is_probationary_provider: false, technician_count: 5, provider_property_distance_in_miles: 23.0, is_provider_recommended_for_job: false, confidence: ConfidenceLevel.CONFIDENCE_LEVEL_UNSPECIFIED, behavior_labels: [] },
      { provider_id: 'ct-prov-012', provider_name: 'Frayser Facility Group', provider_address_id: 'ct-addr-012', score: 53, is_probationary_provider: false, technician_count: 3, provider_property_distance_in_miles: 25.7, is_provider_recommended_for_job: false, confidence: ConfidenceLevel.CONFIDENCE_LEVEL_UNSPECIFIED, behavior_labels: [] },
      { provider_id: 'ct-prov-013', provider_name: 'Raleigh Building Services', provider_address_id: 'ct-addr-013', score: 51, is_probationary_provider: false, technician_count: 4, provider_property_distance_in_miles: 27.4, is_provider_recommended_for_job: false, confidence: ConfidenceLevel.CONFIDENCE_LEVEL_UNSPECIFIED, behavior_labels: [] },
      { provider_id: 'ct-prov-014', provider_name: 'North Memphis Maintenance', provider_address_id: 'ct-addr-014', score: 49, is_probationary_provider: false, technician_count: 6, provider_property_distance_in_miles: 29.1, is_provider_recommended_for_job: false, confidence: ConfidenceLevel.CONFIDENCE_LEVEL_UNSPECIFIED, behavior_labels: [] },
      { provider_id: 'ct-prov-015', provider_name: 'Midtown Handyman Services', provider_address_id: 'ct-addr-015', score: 47, is_probationary_provider: false, technician_count: 5, provider_property_distance_in_miles: 31.8, is_provider_recommended_for_job: false, confidence: ConfidenceLevel.CONFIDENCE_LEVEL_UNSPECIFIED, behavior_labels: [] },
      { provider_id: 'ct-prov-016', provider_name: 'Olive Branch Facilities', provider_address_id: 'ct-addr-016', score: 45, is_probationary_provider: false, technician_count: 7, provider_property_distance_in_miles: 33.5, is_provider_recommended_for_job: false, confidence: ConfidenceLevel.CONFIDENCE_LEVEL_UNSPECIFIED, behavior_labels: [] },
      { provider_id: 'ct-prov-017', provider_name: 'Southaven Maintenance Pro', provider_address_id: 'ct-addr-017', score: 43, is_probationary_provider: false, technician_count: 4, provider_property_distance_in_miles: 35.2, is_provider_recommended_for_job: false, confidence: ConfidenceLevel.CONFIDENCE_LEVEL_UNSPECIFIED, behavior_labels: [] },
      { provider_id: 'ct-prov-018', provider_name: 'Horn Lake Building Group', provider_address_id: 'ct-addr-018', score: 41, is_probationary_provider: false, technician_count: 5, provider_property_distance_in_miles: 38.0, is_provider_recommended_for_job: false, confidence: ConfidenceLevel.CONFIDENCE_LEVEL_UNSPECIFIED, behavior_labels: [] },
      { provider_id: 'ct-prov-019', provider_name: 'West Memphis Facility Services', provider_address_id: 'ct-addr-019', score: 40, is_probationary_provider: false, technician_count: 6, provider_property_distance_in_miles: 40.8, is_provider_recommended_for_job: false, confidence: ConfidenceLevel.CONFIDENCE_LEVEL_UNSPECIFIED, behavior_labels: [] },
    ]
  ),
  filtration_stats: [
    { reason: 'INSURANCE LAPSED OR MISSING', count: 6 },
    { reason: 'NO ACTIVE LICENSE', count: 4 },
    { reason: 'CUSTOMER BLOCK ON FILE', count: 2 },
  ],
};

const CEILING_VERIFY: WorkVerificationReportV2 = {
  work_id: 'DEMO_WV_CEILING_TILE_01',
  report_id: 'rpt-ceiling-001',
  verification_report_status: VerificationReportStatus.VERIFICATION_REPORT_STATUS_COMPLETED,
  work_actions: [
    {
      action_id: 'wa-ct-000',
      type: WorkActionType.WORK_ACTION_TYPE_DOCUMENTATION,
      category: WorkActionCategory.WORK_ACTION_CATEGORY_OTHERS,
      priority: WorkActionPriority.WORK_ACTION_PRIORITY_HIGH,
      description: 'Check in at loading dock, coordinate with stock manager for aisle clearance',
      status: WorkActionStatus.WORK_ACTION_STATUS_COMPLETE,
      status_update_context: { rationale: 'Provider checked in at loading dock and coordinated aisle clearance with stock manager before beginning work.', evidences: [] },
    },
    {
      action_id: 'wa-ct-001a',
      type: WorkActionType.WORK_ACTION_TYPE_DOCUMENTATION,
      category: WorkActionCategory.WORK_ACTION_CATEGORY_INSPECTION,
      priority: WorkActionPriority.WORK_ACTION_PRIORITY_HIGH,
      description: 'Take before photos of all damaged tiles, grid system, and water staining',
      status: WorkActionStatus.WORK_ACTION_STATUS_COMPLETE,
      status_update_context: { rationale: 'Before photos submitted showing 11 sagging tiles with visible water staining and grid damage.', evidences: [{ id: 'ev-ct-before-1', type: EvidenceType.EVIDENCE_TYPE_BEFORE_IMAGES, visit_id: 'visit-ct-001', rationale: 'Before images document full extent of tile damage.' }] },
    },
    {
      action_id: 'wa-ct-002',
      type: WorkActionType.WORK_ACTION_TYPE_ESSENTIAL,
      category: WorkActionCategory.WORK_ACTION_CATEGORY_INSPECTION,
      priority: WorkActionPriority.WORK_ACTION_PRIORITY_HIGH,
      description: 'Remove damaged tiles and inspect above-ceiling space for active leaks or mold',
      status: WorkActionStatus.WORK_ACTION_STATUS_COMPLETE,
      status_update_context: { rationale: 'Above-ceiling inspection revealed dried water stain on HVAC condensate line — no active leak. No mold found.', evidences: [{ id: 'ev-ct-during-1', type: EvidenceType.EVIDENCE_TYPE_DURING_IMAGES, visit_id: 'visit-ct-001', rationale: 'During image shows above-ceiling space with dried stain on condensate line.' }] },
    },
    {
      action_id: 'wa-ct-003',
      type: WorkActionType.WORK_ACTION_TYPE_ESSENTIAL,
      category: WorkActionCategory.WORK_ACTION_CATEGORY_REPLACEMENT,
      priority: WorkActionPriority.WORK_ACTION_PRIORITY_HIGH,
      description: 'Install matching 2x4 acoustic replacement tiles in T-bar grid',
      status: WorkActionStatus.WORK_ACTION_STATUS_COMPLETE,
      status_update_context: { rationale: '11 matching 2x4 Armstrong tiles installed. All seated flush in T-bar grid system.', evidences: [] },
    },
    {
      action_id: 'wa-ct-005',
      type: WorkActionType.WORK_ACTION_TYPE_DOCUMENTATION,
      category: WorkActionCategory.WORK_ACTION_CATEGORY_OTHERS,
      priority: WorkActionPriority.WORK_ACTION_PRIORITY_HIGH,
      description: 'After photos of completed ceiling and stock manager sign-off',
      status: WorkActionStatus.WORK_ACTION_STATUS_COMPLETE,
      status_update_context: { rationale: 'After photos show completed ceiling with all new tiles installed flush. Manager sign-off obtained.', evidences: [{ id: 'ev-ct-after-1', type: EvidenceType.EVIDENCE_TYPE_AFTER_IMAGES, visit_id: 'visit-ct-001', rationale: 'After images confirm completed tile installation.' }] },
    },
  ],
  image_analyses: [
    { image_id: 'img-ct-before-1', analysis: 'Sagging and water-stained ceiling tiles in stockroom', evidence_type: EvidenceType.EVIDENCE_TYPE_BEFORE_IMAGES },
    { image_id: 'img-ct-during-1', analysis: 'Above-ceiling view showing dried condensate stain on HVAC line', evidence_type: EvidenceType.EVIDENCE_TYPE_DURING_IMAGES },
    { image_id: 'img-ct-after-1', analysis: 'Completed ceiling with new tiles installed flush in T-bar grid', evidence_type: EvidenceType.EVIDENCE_TYPE_AFTER_IMAGES },
  ],
  verification_results: {
    complete_reason: 'All essential ceiling tile replacement tasks completed. 11 tiles replaced and documented.',
    work_completion_status: WorkCompletionStatus.WORK_COMPLETION_STATUS_COMPLETE,
    work_completion_confidence: ConfidenceLevel.CONFIDENCE_LEVEL_HIGH,
    labor_hours_assessment: { is_appropriate: true, confidence: ConfidenceLevel.CONFIDENCE_LEVEL_HIGH, labor_prediction_id: 'labor-pred-ceiling-001' },
    work_verification_rationale: 'Ceiling tile replacement completed as scoped. 11 tiles replaced with matching Armstrong 2x4 acoustic tiles. Above-ceiling inspection documented a past (dried) condensate leak with no active moisture. No mold found. Before and after photos confirm full scope completion.',
  },
};

// ─── Routine Landscaping (CSA) ────────────────────────────────────────────────

const LANDSCAPING_QUALIFY: PredictionResponse = {
  is_recall: false,
  is_recall_v2: false,
  is_estimate: false,
  is_parts_and_order: false,
  service_type_id: 'svc-type-landscaping-mowing',
  service_line_id: 'svc-line-landscaping',
  is_project_work: false,
  enriched_ticket_scope:
    'Scheduled monthly grounds maintenance at strip mall: mowing all turf areas, string trimming, edging along hardscapes, debris cleanup, and weed control in landscape beds.',
  work_scope:
    'Mow all turf areas per agreed frequency. Mulch clippings or remove excessive clumps. Sweep and blow all clippings from walks, patios, curbs, and drainage outlets. String trim all areas inaccessible to mower. Edge along sidewalks, driveways, curbs, parking lots, landscape beds, and fence lines. Remove all trash and debris from property. Pull weeds from mulch and rock beds. Apply weed control in greenspace and hardscape areas. No herbicides near water features.',
  work_type: 'MAINTENANCE',
  asset: 'Exterior Grounds',
  location: 'Full Property Exterior',
  special_instructions:
    'Notify property manager on arrival and departure. All equipment blades maintained sharp for uniform cut. Avoid blower spray into planting beds.',
  recommendation_id: 'rec-landscape-001',
  work_complexity: 'SIMPLE',
};

const LANDSCAPING_WORK_ACTIONS: WorkAction[] = [
  {
    action_id: 'wa-ls-000',
    type: WorkActionType.WORK_ACTION_TYPE_DOCUMENTATION,
    category: WorkActionCategory.WORK_ACTION_CATEGORY_OTHERS,
    priority: WorkActionPriority.WORK_ACTION_PRIORITY_HIGH,
    description: 'Check in with property manager on arrival and confirm service scope for this visit',
    status: WorkActionStatus.WORK_ACTION_STATUS_TODO,
    creation_context: { rationale: 'Property manager notification required per special instructions at arrival and departure.', evidences: [] },
  },
  {
    action_id: 'wa-ls-001a',
    type: WorkActionType.WORK_ACTION_TYPE_DOCUMENTATION,
    category: WorkActionCategory.WORK_ACTION_CATEGORY_INSPECTION,
    priority: WorkActionPriority.WORK_ACTION_PRIORITY_HIGH,
    description: 'Take before photos of all turf areas, landscape beds, and hardscape edges documenting pre-service condition',
    status: WorkActionStatus.WORK_ACTION_STATUS_TODO,
    creation_context: { rationale: 'Before photos establish baseline for quality verification of mowing height and grounds condition.', evidences: [] },
  },
  {
    action_id: 'wa-ls-001',
    type: WorkActionType.WORK_ACTION_TYPE_ESSENTIAL,
    category: WorkActionCategory.WORK_ACTION_CATEGORY_MAINTENANCE,
    priority: WorkActionPriority.WORK_ACTION_PRIORITY_HIGH,
    description: 'Mow all turf areas per agreed frequency schedule — use sharp mulching blades and distribute or remove excessive clippings',
    status: WorkActionStatus.WORK_ACTION_STATUS_TODO,
    creation_context: { rationale: 'Primary scope deliverable. Sharp blades required for uniform cut per contract terms.', evidences: [] },
  },
  {
    action_id: 'wa-ls-002',
    type: WorkActionType.WORK_ACTION_TYPE_ESSENTIAL,
    category: WorkActionCategory.WORK_ACTION_CATEGORY_MAINTENANCE,
    priority: WorkActionPriority.WORK_ACTION_PRIORITY_HIGH,
    description: 'String trim all turf areas inaccessible to mowing equipment — maintain consistent turf height throughout property',
    status: WorkActionStatus.WORK_ACTION_STATUS_TODO,
    creation_context: { rationale: 'String trimming ensures uniform appearance in areas the mower cannot reach.', evidences: [] },
  },
  {
    action_id: 'wa-ls-003',
    type: WorkActionType.WORK_ACTION_TYPE_ESSENTIAL,
    category: WorkActionCategory.WORK_ACTION_CATEGORY_MAINTENANCE,
    priority: WorkActionPriority.WORK_ACTION_PRIORITY_HIGH,
    description: 'Edge along all sidewalks, driveways, curbs, parking lot borders, landscape beds, and fence lines for clean uniform appearance',
    status: WorkActionStatus.WORK_ACTION_STATUS_TODO,
    creation_context: { rationale: 'Edging all hardscape borders is a core contract deliverable for professional appearance.', evidences: [] },
  },
  {
    action_id: 'wa-ls-004',
    type: WorkActionType.WORK_ACTION_TYPE_ESSENTIAL,
    category: WorkActionCategory.WORK_ACTION_CATEGORY_CLEANING,
    priority: WorkActionPriority.WORK_ACTION_PRIORITY_HIGH,
    description: 'Sweep and blow all clippings, organic debris, and displaced mulch from walks, patios, curbs, curb corners, and drainage outlets',
    status: WorkActionStatus.WORK_ACTION_STATUS_TODO,
    creation_context: { rationale: 'Blowout of all hard surfaces is required to leave property clean after service. Avoid blower spray into planting beds.', evidences: [] },
  },
  {
    action_id: 'wa-ls-005',
    type: WorkActionType.WORK_ACTION_TYPE_ESSENTIAL,
    category: WorkActionCategory.WORK_ACTION_CATEGORY_MAINTENANCE,
    priority: WorkActionPriority.WORK_ACTION_PRIORITY_MEDIUM,
    description: 'Remove all trash, paper, and debris from property. Pull weeds from mulch beds, rock beds, and hardscape areas',
    status: WorkActionStatus.WORK_ACTION_STATUS_TODO,
    creation_context: { rationale: 'Debris removal and weed control in all bed and hardscape areas is included in monthly CSA scope.', evidences: [] },
  },
  {
    action_id: 'wa-ls-006',
    type: WorkActionType.WORK_ACTION_TYPE_DOCUMENTATION,
    category: WorkActionCategory.WORK_ACTION_CATEGORY_OTHERS,
    priority: WorkActionPriority.WORK_ACTION_PRIORITY_HIGH,
    description: 'Take after photos of completed mowing, trimmed edges, clean hardscapes, and tidy landscape beds — notify property manager on departure',
    status: WorkActionStatus.WORK_ACTION_STATUS_TODO,
    creation_context: { rationale: 'After photos confirm full scope completion. Manager departure notification required per contract.', evidences: [] },
  },
];

const LANDSCAPING_MATCH: MatchResponse & { is_csa_assignment: boolean } = {
  total_matched: 1,
  is_csa_assignment: true,
  providers: [
    {
      provider_id: 'csa-ls-prov-001',
      provider_name: 'Greenscape Property Services',
      provider_address_id: 'csa-ls-addr-001',
      score: 95,
      is_probationary_provider: false,
      technician_count: 6,
      provider_property_distance_in_miles: 7.8,
      tags: [],
      is_provider_recommended_for_job: true,
      ai_rationale: 'Contracted CSA provider for this property. Active Customer Schedule Activity agreement in place. Auto-dispatched per contract terms.',
      confidence: ConfidenceLevel.CONFIDENCE_LEVEL_HIGH,
      behavior_labels: ['customer_veteran', 'property_veteran'],
      speed_score: 92,
      quality_score: 96,
      cost_score: 94,
      rating: 4.9,
      review_count: 287,
      jobs_completed: 624,
      scorecard_details: {
        speed: { overall: 92, on_time_arrival: 94, time_to_work_done: 90 },
        quality: { overall: 96, first_time_complete: 95, defect_free_jobs: 98, app_compliance: 96 },
        cost: { overall: 94, used_under_nte: 92, dispute_free: 97 },
      },
    },
  ],
  filtration_stats: [],
};

const LANDSCAPING_VERIFY: WorkVerificationReportV2 = {
  work_id: 'DEMO_WV_LANDSCAPING_01',
  report_id: 'rpt-landscape-001',
  verification_report_status: VerificationReportStatus.VERIFICATION_REPORT_STATUS_COMPLETED,
  work_actions: [
    {
      action_id: 'wa-ls-001',
      type: WorkActionType.WORK_ACTION_TYPE_ESSENTIAL,
      category: WorkActionCategory.WORK_ACTION_CATEGORY_MAINTENANCE,
      priority: WorkActionPriority.WORK_ACTION_PRIORITY_HIGH,
      description: 'Mow all turf areas per agreed frequency schedule',
      status: WorkActionStatus.WORK_ACTION_STATUS_COMPLETE,
      status_update_context: { rationale: 'Before and after photos confirm all turf areas mowed to uniform height. Clippings mulched in place.', evidences: [{ id: 'ev-ls-before-1', type: EvidenceType.EVIDENCE_TYPE_BEFORE_IMAGES, visit_id: 'visit-ls-001', rationale: 'Before photos show turf at pre-service height.' }, { id: 'ev-ls-after-1', type: EvidenceType.EVIDENCE_TYPE_AFTER_IMAGES, visit_id: 'visit-ls-001', rationale: 'After photos confirm uniform mow height.' }] },
    },
    {
      action_id: 'wa-ls-002',
      type: WorkActionType.WORK_ACTION_TYPE_ESSENTIAL,
      category: WorkActionCategory.WORK_ACTION_CATEGORY_MAINTENANCE,
      priority: WorkActionPriority.WORK_ACTION_PRIORITY_HIGH,
      description: 'String trim all inaccessible turf areas',
      status: WorkActionStatus.WORK_ACTION_STATUS_COMPLETE,
      status_update_context: { rationale: 'After photos show trimmed edges around obstacles, curbs, and sign posts throughout property.', evidences: [] },
    },
    {
      action_id: 'wa-ls-003',
      type: WorkActionType.WORK_ACTION_TYPE_ESSENTIAL,
      category: WorkActionCategory.WORK_ACTION_CATEGORY_MAINTENANCE,
      priority: WorkActionPriority.WORK_ACTION_PRIORITY_HIGH,
      description: 'Edge along all sidewalks, driveways, curbs, and landscape beds',
      status: WorkActionStatus.WORK_ACTION_STATUS_COMPLETE,
      status_update_context: { rationale: 'Clean, sharp edging visible along all hardscape borders in after photos.', evidences: [] },
    },
    {
      action_id: 'wa-ls-004',
      type: WorkActionType.WORK_ACTION_TYPE_ESSENTIAL,
      category: WorkActionCategory.WORK_ACTION_CATEGORY_CLEANING,
      priority: WorkActionPriority.WORK_ACTION_PRIORITY_HIGH,
      description: 'Blow all clippings from hard surfaces',
      status: WorkActionStatus.WORK_ACTION_STATUS_COMPLETE,
      status_update_context: { rationale: 'All walkways, parking areas, and curb edges clean of clippings in after photos.', evidences: [] },
    },
    {
      action_id: 'wa-ls-006',
      type: WorkActionType.WORK_ACTION_TYPE_DOCUMENTATION,
      category: WorkActionCategory.WORK_ACTION_CATEGORY_OTHERS,
      priority: WorkActionPriority.WORK_ACTION_PRIORITY_HIGH,
      description: 'After photos and property manager departure notification',
      status: WorkActionStatus.WORK_ACTION_STATUS_COMPLETE,
      status_update_context: { rationale: 'After photos submitted confirming all scope deliverables. Manager notified on departure per contract terms.', evidences: [{ id: 'ev-ls-after-2', type: EvidenceType.EVIDENCE_TYPE_AFTER_IMAGES, visit_id: 'visit-ls-001', rationale: 'After images document completed grounds maintenance.' }] },
    },
  ],
  image_analyses: [
    { image_id: 'img-ls-before-1', analysis: 'Turf areas showing growth exceeding agreed mow height', evidence_type: EvidenceType.EVIDENCE_TYPE_BEFORE_IMAGES },
    { image_id: 'img-ls-before-2', analysis: 'Landscape bed edges showing overgrowth and weed presence', evidence_type: EvidenceType.EVIDENCE_TYPE_BEFORE_IMAGES },
    { image_id: 'img-ls-after-1', analysis: 'Uniformly mowed turf across all areas at proper height', evidence_type: EvidenceType.EVIDENCE_TYPE_AFTER_IMAGES },
    { image_id: 'img-ls-after-2', analysis: 'Clean edging along curb and sidewalk borders', evidence_type: EvidenceType.EVIDENCE_TYPE_AFTER_IMAGES },
    { image_id: 'img-ls-after-3', analysis: 'Clean hardscape with no clipping debris visible', evidence_type: EvidenceType.EVIDENCE_TYPE_AFTER_IMAGES },
  ],
  verification_results: {
    complete_reason: 'All essential grounds maintenance tasks completed and documented per CSA agreement.',
    work_completion_status: WorkCompletionStatus.WORK_COMPLETION_STATUS_COMPLETE,
    work_completion_confidence: ConfidenceLevel.CONFIDENCE_LEVEL_HIGH,
    labor_hours_assessment: { is_appropriate: true, confidence: ConfidenceLevel.CONFIDENCE_LEVEL_HIGH, labor_prediction_id: 'labor-pred-ls-001' },
    work_verification_rationale: 'Routine landscaping service completed per CSA scope. Before and after photos confirm mowing, trimming, edging, and cleanup all completed to standard. Property returned to clean condition per contract terms.',
  },
};

// ─── Snow Removal (CSA) ───────────────────────────────────────────────────────

const SNOW_QUALIFY: PredictionResponse = {
  is_recall: false,
  is_recall_v2: false,
  is_estimate: false,
  is_parts_and_order: false,
  service_type_id: 'svc-type-snow-plowing',
  service_line_id: 'svc-line-snow-removal',
  is_project_work: false,
  enriched_ticket_scope:
    'Overnight 4-6 inch snowfall at grocery store. Parking lot, fire lanes, and sidewalks require plowing and salt treatment before 7 AM store opening. Contracted CSA provider dispatched.',
  work_scope:
    'Apply pre-treatment salt brine to fire lanes and primary pedestrian paths before plowing. Plow all parking lot areas pushing snow to designated pile locations away from fire hydrants and dumpster access. Plow fire lanes to clear width. Hand-shovel and clear all sidewalks and building entrances. Apply granular salt to all plowed surfaces for ice prevention. Document completion with photos before 7 AM.',
  work_type: 'MAINTENANCE',
  asset: 'Parking Lot / Sidewalks',
  location: 'Full Property Exterior',
  special_instructions:
    'Must be complete before 7 AM store open. Do not block fire hydrants or cart return areas with snow piles. Contact store manager on arrival.',
  recommendation_id: 'rec-snow-001',
  work_complexity: 'SIMPLE',
};

const SNOW_WORK_ACTIONS: WorkAction[] = [
  {
    action_id: 'wa-sn-000',
    type: WorkActionType.WORK_ACTION_TYPE_DOCUMENTATION,
    category: WorkActionCategory.WORK_ACTION_CATEGORY_OTHERS,
    priority: WorkActionPriority.WORK_ACTION_PRIORITY_HIGH,
    description: 'Contact store manager on arrival — confirm priority areas and snow pile location designations',
    status: WorkActionStatus.WORK_ACTION_STATUS_TODO,
    creation_context: { rationale: 'Manager coordination required per special instructions to confirm pile locations and priority areas before work begins.', evidences: [] },
  },
  {
    action_id: 'wa-sn-001a',
    type: WorkActionType.WORK_ACTION_TYPE_DOCUMENTATION,
    category: WorkActionCategory.WORK_ACTION_CATEGORY_INSPECTION,
    priority: WorkActionPriority.WORK_ACTION_PRIORITY_HIGH,
    description: 'Take before photos of full parking lot, fire lanes, and sidewalks showing snowfall depth and coverage',
    status: WorkActionStatus.WORK_ACTION_STATUS_TODO,
    creation_context: { rationale: 'Before photos document snowfall extent and condition for quality verification and billing records.', evidences: [] },
  },
  {
    action_id: 'wa-sn-001',
    type: WorkActionType.WORK_ACTION_TYPE_ESSENTIAL,
    category: WorkActionCategory.WORK_ACTION_CATEGORY_MAINTENANCE,
    priority: WorkActionPriority.WORK_ACTION_PRIORITY_HIGH,
    description: 'Apply pre-treatment salt brine to fire lanes and primary pedestrian entry paths',
    status: WorkActionStatus.WORK_ACTION_STATUS_TODO,
    creation_context: { rationale: 'Pre-treatment brine prevents ice bonding before plowing begins, critical for fire lane safety.', evidences: [] },
  },
  {
    action_id: 'wa-sn-002',
    type: WorkActionType.WORK_ACTION_TYPE_ESSENTIAL,
    category: WorkActionCategory.WORK_ACTION_CATEGORY_MAINTENANCE,
    priority: WorkActionPriority.WORK_ACTION_PRIORITY_HIGH,
    description: 'Plow all parking lot areas — push snow to designated pile locations away from fire hydrants, cart returns, and dumpster access',
    status: WorkActionStatus.WORK_ACTION_STATUS_TODO,
    creation_context: { rationale: 'Full parking lot plowing is the primary scope deliverable. Pile locations must comply with fire code and site rules.', evidences: [] },
  },
  {
    action_id: 'wa-sn-003',
    type: WorkActionType.WORK_ACTION_TYPE_ESSENTIAL,
    category: WorkActionCategory.WORK_ACTION_CATEGORY_MAINTENANCE,
    priority: WorkActionPriority.WORK_ACTION_PRIORITY_HIGH,
    description: 'Plow fire lanes to full clear width — verify no snow within fire lane markings',
    status: WorkActionStatus.WORK_ACTION_STATUS_TODO,
    creation_context: { rationale: 'Fire lane clearance is a safety and code requirement. Must be fully clear before store opens.', evidences: [] },
  },
  {
    action_id: 'wa-sn-004',
    type: WorkActionType.WORK_ACTION_TYPE_ESSENTIAL,
    category: WorkActionCategory.WORK_ACTION_CATEGORY_MAINTENANCE,
    priority: WorkActionPriority.WORK_ACTION_PRIORITY_HIGH,
    description: 'Hand-shovel all sidewalks and building entrances — clear to bare pavement',
    status: WorkActionStatus.WORK_ACTION_STATUS_TODO,
    creation_context: { rationale: 'Sidewalks and entrances require manual clearing to bare pavement for pedestrian safety.', evidences: [] },
  },
  {
    action_id: 'wa-sn-005',
    type: WorkActionType.WORK_ACTION_TYPE_ESSENTIAL,
    category: WorkActionCategory.WORK_ACTION_CATEGORY_MAINTENANCE,
    priority: WorkActionPriority.WORK_ACTION_PRIORITY_HIGH,
    description: 'Apply granular salt to all plowed surfaces — parking lot, fire lanes, sidewalks, and building entrances',
    status: WorkActionStatus.WORK_ACTION_STATUS_TODO,
    creation_context: { rationale: 'Post-plow salting prevents ice reformation before and during store open hours.', evidences: [] },
  },
  {
    action_id: 'wa-sn-006',
    type: WorkActionType.WORK_ACTION_TYPE_DOCUMENTATION,
    category: WorkActionCategory.WORK_ACTION_CATEGORY_OTHERS,
    priority: WorkActionPriority.WORK_ACTION_PRIORITY_HIGH,
    description: 'Take after photos of cleared parking lot, fire lanes, sidewalks, and entrances — document completion timestamp before 7 AM open',
    status: WorkActionStatus.WORK_ACTION_STATUS_TODO,
    creation_context: { rationale: 'After photos with timestamp confirm completion before store open deadline. Required for CSA billing record.', evidences: [] },
  },
];

const SNOW_MATCH: MatchResponse & { is_csa_assignment: boolean } = {
  total_matched: 1,
  is_csa_assignment: true,
  providers: [
    {
      provider_id: 'csa-sn-prov-001',
      provider_name: 'Arctic Plow & Salt Services',
      provider_address_id: 'csa-sn-addr-001',
      score: 95,
      is_probationary_provider: false,
      technician_count: 8,
      provider_property_distance_in_miles: 6.4,
      tags: [],
      is_provider_recommended_for_job: true,
      ai_rationale: 'Contracted CSA provider for this property. Active Customer Schedule Activity agreement for snow removal. Auto-dispatched per contract terms on snowfall trigger.',
      confidence: ConfidenceLevel.CONFIDENCE_LEVEL_HIGH,
      behavior_labels: ['customer_veteran', 'property_veteran'],
      speed_score: 94,
      quality_score: 97,
      cost_score: 92,
      rating: 4.9,
      review_count: 341,
      jobs_completed: 892,
      scorecard_details: {
        speed: { overall: 94, on_time_arrival: 96, time_to_work_done: 92 },
        quality: { overall: 97, first_time_complete: 96, defect_free_jobs: 99, app_compliance: 97 },
        cost: { overall: 92, used_under_nte: 90, dispute_free: 95 },
      },
    },
  ],
  filtration_stats: [],
};

const SNOW_VERIFY: WorkVerificationReportV2 = {
  work_id: 'DEMO_WV_SNOW_REMOVAL_01',
  report_id: 'rpt-snow-001',
  verification_report_status: VerificationReportStatus.VERIFICATION_REPORT_STATUS_COMPLETED,
  work_actions: [
    {
      action_id: 'wa-sn-001',
      type: WorkActionType.WORK_ACTION_TYPE_ESSENTIAL,
      category: WorkActionCategory.WORK_ACTION_CATEGORY_MAINTENANCE,
      priority: WorkActionPriority.WORK_ACTION_PRIORITY_HIGH,
      description: 'Apply pre-treatment salt brine to fire lanes and primary pedestrian paths',
      status: WorkActionStatus.WORK_ACTION_STATUS_COMPLETE,
      status_update_context: { rationale: 'Pre-treatment brine applied to fire lanes and main entry paths before plowing began.', evidences: [] },
    },
    {
      action_id: 'wa-sn-002',
      type: WorkActionType.WORK_ACTION_TYPE_ESSENTIAL,
      category: WorkActionCategory.WORK_ACTION_CATEGORY_MAINTENANCE,
      priority: WorkActionPriority.WORK_ACTION_PRIORITY_HIGH,
      description: 'Plow all parking lot areas to designated pile locations',
      status: WorkActionStatus.WORK_ACTION_STATUS_COMPLETE,
      status_update_context: { rationale: 'Full parking lot plowed. Snow pushed to designated corner pile areas. No hydrants or cart returns blocked.', evidences: [{ id: 'ev-sn-after-1', type: EvidenceType.EVIDENCE_TYPE_AFTER_IMAGES, visit_id: 'visit-sn-001', rationale: 'After photos confirm cleared lot with compliant pile placement.' }] },
    },
    {
      action_id: 'wa-sn-003',
      type: WorkActionType.WORK_ACTION_TYPE_ESSENTIAL,
      category: WorkActionCategory.WORK_ACTION_CATEGORY_MAINTENANCE,
      priority: WorkActionPriority.WORK_ACTION_PRIORITY_HIGH,
      description: 'Plow fire lanes to full clear width',
      status: WorkActionStatus.WORK_ACTION_STATUS_COMPLETE,
      status_update_context: { rationale: 'Fire lanes plowed to bare pavement. After photos confirm no snow within fire lane markings.', evidences: [] },
    },
    {
      action_id: 'wa-sn-004',
      type: WorkActionType.WORK_ACTION_TYPE_ESSENTIAL,
      category: WorkActionCategory.WORK_ACTION_CATEGORY_MAINTENANCE,
      priority: WorkActionPriority.WORK_ACTION_PRIORITY_HIGH,
      description: 'Hand-shovel all sidewalks and building entrances',
      status: WorkActionStatus.WORK_ACTION_STATUS_COMPLETE,
      status_update_context: { rationale: 'All sidewalks and entrances hand-shoveled to bare pavement. After photos confirm clear access paths.', evidences: [] },
    },
    {
      action_id: 'wa-sn-006',
      type: WorkActionType.WORK_ACTION_TYPE_DOCUMENTATION,
      category: WorkActionCategory.WORK_ACTION_CATEGORY_OTHERS,
      priority: WorkActionPriority.WORK_ACTION_PRIORITY_HIGH,
      description: 'After photos with timestamp confirming completion before 7 AM',
      status: WorkActionStatus.WORK_ACTION_STATUS_COMPLETE,
      status_update_context: { rationale: 'After photos timestamped at 6:42 AM confirming full completion before store open. All surfaces cleared and salted.', evidences: [{ id: 'ev-sn-after-2', type: EvidenceType.EVIDENCE_TYPE_AFTER_IMAGES, visit_id: 'visit-sn-001', rationale: 'Timestamped after photos document completion before 7 AM deadline.' }] },
    },
  ],
  image_analyses: [
    { image_id: 'img-sn-before-1', analysis: 'Parking lot with 4-6 inch snow coverage across all surfaces', evidence_type: EvidenceType.EVIDENCE_TYPE_BEFORE_IMAGES },
    { image_id: 'img-sn-before-2', analysis: 'Sidewalks and entrance completely covered in snow', evidence_type: EvidenceType.EVIDENCE_TYPE_BEFORE_IMAGES },
    { image_id: 'img-sn-after-1', analysis: 'Cleared parking lot with snow piled at far corners away from hydrants', evidence_type: EvidenceType.EVIDENCE_TYPE_AFTER_IMAGES },
    { image_id: 'img-sn-after-2', analysis: 'Clear fire lanes and entrance sidewalks with granular salt visible', evidence_type: EvidenceType.EVIDENCE_TYPE_AFTER_IMAGES },
  ],
  verification_results: {
    complete_reason: 'All essential snow removal tasks completed before 7 AM deadline per CSA contract terms.',
    work_completion_status: WorkCompletionStatus.WORK_COMPLETION_STATUS_COMPLETE,
    work_completion_confidence: ConfidenceLevel.CONFIDENCE_LEVEL_HIGH,
    labor_hours_assessment: { is_appropriate: true, confidence: ConfidenceLevel.CONFIDENCE_LEVEL_HIGH, labor_prediction_id: 'labor-pred-snow-001' },
    work_verification_rationale: 'Snow removal completed before the required 7 AM store open deadline (timestamped 6:42 AM). Full lot plowed, fire lanes cleared, sidewalks hand-shoveled, and all surfaces salted. Photo evidence confirms compliant pile placement and clear pedestrian access.',
  },
};

// ─── Scenario Mock Map ────────────────────────────────────────────────────────

type ScenarioMock = {
  qualify: PredictionResponse;
  workActions: WorkAction[];
  match: MatchResponse;
  verify: WorkVerificationReportV2;
};

const SCENARIO_MOCK_MAP: Record<string, ScenarioMock> = {
  'hot-water-heater': {
    qualify: MOCK_QUALIFY_RESPONSE,
    workActions: MOCK_WORK_ACTIONS,
    match: MOCK_MATCH_RESPONSE,
    verify: MOCK_VERIFY_RESPONSE,
  },
  'hvac-not-cooling': {
    qualify: HVAC_QUALIFY,
    workActions: HVAC_WORK_ACTIONS,
    match: HVAC_MATCH,
    verify: HVAC_VERIFY,
  },
  'ceiling-tile-damage': {
    qualify: CEILING_QUALIFY,
    workActions: CEILING_WORK_ACTIONS,
    match: CEILING_MATCH,
    verify: CEILING_VERIFY,
  },
  'routine-landscaping': {
    qualify: LANDSCAPING_QUALIFY,
    workActions: LANDSCAPING_WORK_ACTIONS,
    match: LANDSCAPING_MATCH as MatchResponse,
    verify: LANDSCAPING_VERIFY,
  },
  'snow-removal': {
    qualify: SNOW_QUALIFY,
    workActions: SNOW_WORK_ACTIONS,
    match: SNOW_MATCH as MatchResponse,
    verify: SNOW_VERIFY,
  },
};

export function getMockForScenario(scenarioId: string): ScenarioMock {
  return SCENARIO_MOCK_MAP[scenarioId] ?? SCENARIO_MOCK_MAP['hot-water-heater'];
}
